#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pytest_randomly
Version  : 3.11.0
Release  : 42
URL      : https://files.pythonhosted.org/packages/79/98/ab901d5beda6990d37f79cafdb611d794cf638767827c3d479d078821d35/pytest-randomly-3.11.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/79/98/ab901d5beda6990d37f79cafdb611d794cf638767827c3d479d078821d35/pytest-randomly-3.11.0.tar.gz
Summary  : Pytest plugin to randomly order tests and control random.seed.
Group    : Development/Tools
License  : MIT
Requires: pypi-pytest_randomly-license = %{version}-%{release}
Requires: pypi-pytest_randomly-python = %{version}-%{release}
Requires: pypi-pytest_randomly-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(importlib_metadata)
BuildRequires : pypi(pytest)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)

%description
===============
pytest-randomly
===============
.. image:: https://img.shields.io/github/workflow/status/pytest-dev/pytest-randomly/CI/main?style=for-the-badge
:target: https://github.com/pytest-dev/pytest-randomly/actions?workflow=CI

%package license
Summary: license components for the pypi-pytest_randomly package.
Group: Default

%description license
license components for the pypi-pytest_randomly package.


%package python
Summary: python components for the pypi-pytest_randomly package.
Group: Default
Requires: pypi-pytest_randomly-python3 = %{version}-%{release}

%description python
python components for the pypi-pytest_randomly package.


%package python3
Summary: python3 components for the pypi-pytest_randomly package.
Group: Default
Requires: python3-core
Provides: pypi(pytest_randomly)
Requires: pypi(importlib_metadata)
Requires: pypi(pytest)

%description python3
python3 components for the pypi-pytest_randomly package.


%prep
%setup -q -n pytest-randomly-3.11.0
cd %{_builddir}/pytest-randomly-3.11.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641941711
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pytest_randomly
cp %{_builddir}/pytest-randomly-3.11.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pytest_randomly/357dd8dc959a96d3bc13e11e940ccc7dd955492b
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pytest_randomly/357dd8dc959a96d3bc13e11e940ccc7dd955492b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
